# Generated by Django 4.0.1 on 2022-01-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul', models.CharField(max_length=64)),
                ('Opis', models.CharField(max_length=128)),
                ('Tresc', models.TextField()),
                ('Data', models.DateTimeField()),
            ],
        ),
    ]
