# Generated by Django 4.0.1 on 2022-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigPastaApp', '0003_alter_pasta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='Data',
            field=models.DateField(),
        ),
    ]
