# Generated by Django 4.0.1 on 2022-01-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigPastaApp', '0004_alter_pasta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='Data',
        ),
    ]
